name: "release"

on:
  push:
    tags:
    - '**'

jobs:
  build:
    runs-on: cimg/rust:1.82.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.82.0
      - run: cargo build --release --package cbor-diag-cli
      - uses: actions/upload-artifact@v2
        with:
          path: './target/release/cbor-diag'
